---
all:
  children:
    ios:
      children:
        branch_syd01:
          hosts:
            syd01-R1:
              ansible_host: 10.0.12.2
            syd01-R2:
              ansible_host: 10.0.13.2
          vars:
            base_snmp_location: "Sydney branch 01, Level 2 comms room"